# Generated by Django 5.2.8 on 2025-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_product_foodentry_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='initial_amount',
            field=models.FloatField(default=0, help_text='grams - initial amount when created'),
        ),
    ]
