# Generated by Django 5.2.8 on 2025-12-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_foodentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mealentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodProduct',
        ),
        migrations.DeleteModel(
            name='MealEntry',
        ),
    ]
