# Generated by Django 5.2.8 on 2025-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_entry_carbs_per100_entry_fat_per100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
