# Generated by Django 5.2.8 on 2025-11-27 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories_per_100g', models.FloatField(default=0)),
                ('protein_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='grams')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='cm', null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('1.2', 'Сидячий (мало активности)'), ('1.375', 'Легкая активность'), ('1.55', 'Умеренная активность'), ('1.725', 'Высокая активность'), ('1.9', 'Очень активный')], max_length=10)),
                ('goal', models.CharField(blank=True, choices=[('lose', 'Похудеть'), ('maintain', 'Поддержать вес'), ('gain', 'Набрать вес')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
