# Generated by Django 5.2.8 on 2025-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_remove_mealentry_product_remove_mealentry_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='carbs_per100',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='fat_per100',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='kcal_per100',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='protein_per100',
            field=models.FloatField(default=0.0),
        ),
    ]
